apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: tweets-queue
  namespace: default
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  - name: redisMaxRetries
    value: 5
